import c2pa
import json
import os

class VeritasHybridRouter:
    def __init__(self, ai_auditor=None):
        # Allow injecting the loaded auditor so we don't reload heavy models
        self.ai_auditor = ai_auditor
        self.ai_fallback_enabled = ai_auditor is not None

    def extract_c2pa_manifest(self, file_path):
        """
        Scans the media file for cryptographic Content Credentials.
        Returns the active manifest dictionary if found, or None if stripped/absent.
        """
        try:
            # We pass the file path directly to the Rust backend.
            # Passing a Python file stream over FFI for an 11.5MB file can cause severe memory buffering hangs.
            try:
                # c2pa-python usually accepts the file path string directly
                reader = c2pa.Reader(file_path)
            except Exception:
                # Fallback if the library requires a stream for specific versions, but read the whole file to memory first to avoid FFI stream deadlocks
                ext = os.path.splitext(file_path)[1].lower()
                mime_type = "audio/mpeg" if ext == ".mp3" else "audio/wav"
                with open(file_path, "rb") as file_stream:
                    file_bytes = file_stream.read()
                
                # Import io locally for the fallback
                import io
                reader = c2pa.Reader(mime_type, io.BytesIO(file_bytes))

            manifest_store = json.loads(reader.json())
                    
            # A file can have a history of edits (multiple manifests). 
            # We want the most recent 'active' state.
            active_manifest_label = manifest_store.get("active_manifest")
            
            if active_manifest_label:
                return manifest_store["manifests"][active_manifest_label]
        except Exception as e:
            # If the file has no manifest, or it was stripped, the library throws an exception.
            # We catch it silently so we can trigger the AI fallback.
            return None

    def audit_media(self, file_path):
        """
        Executes the 2026 enterprise standard hybrid audit.
        """
        # STEP 1: The Active Provenance Check (Zero Compute, 100% Certainty)
        manifest = self.extract_c2pa_manifest(file_path)
        
        if manifest:
            # We found a crypto signature! We extract who/what generated it.
            generator = manifest.get("claim_generator", "Unknown Software")
            
            # We bypass the AI model entirely and output absolute certainty.
            return {
                "verdict": "SYNTHETIC",
                "certainty_mechanism": "Cryptographic C2PA Manifest",
                "confidence": 100.0,
                "rationale": f"Unalterable cryptographic C2PA signature detected. Generated by: {generator}",
                "origin_data": generator,
                "status": "error"
            }
            
        # STEP 2: The Passive AI Fallback (High Compute, Probabilistic)
        if self.ai_fallback_enabled:
            scores = self.ai_auditor.verify(file_path)
            verdict, rationale = self.ai_auditor.get_verdict(scores, file_path)
            
            # Extract scores safely handling case issues
            fake_score = scores.get("Fake", scores.get("fake", scores.get("LABEL_1", 0)))
            real_score = scores.get("Real", scores.get("real", scores.get("LABEL_0", 0)))
            
            if "Synthetic" in verdict:
                status = "error"
                confidence = fake_score
            elif "Inconclusive" in verdict:
                status = "warning"
                confidence = fake_score if fake_score > real_score else real_score
            else:
                status = "success"
                confidence = real_score
                
            return {
                "verdict": verdict.upper(),
                "certainty_mechanism": "AI Ensemble Inference (Wav2Vec2 + DSP)",
                "confidence": confidence,
                "rationale": f"No C2PA metadata found (Stripped or Authentic). AI Fallback initiated. {rationale}",
                "origin_data": "Unknown (Stripped/Missing Metadata)",
                "status": status,
                "metadata": {
                    "raw_scores": scores,
                    "dsp_features": self.ai_auditor.last_dsp_features
                }
            }
        
        # If no AI auditor provided
        return {
                "verdict": "UNKNOWN",
                "certainty_mechanism": "None",
                "confidence": 0.0,
                "rationale": "No C2PA metadata found and AI Fallback is disabled.",
                "origin_data": "Unknown",
                "status": "warning"
            }
